name: New Relic Introspector Node
permissions:
  contents: read

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Install Dependencies
      run: npm install
    - name: Run Linting
      run: npm run lint
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Install Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run unit
    - name: Post Unit Test Coverage
      # v7.0.0
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        flags: unit-tests-${{ matrix.node-version }}
